# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:48
from __future__ import unicode_literals

import beerdiary_server.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breweries', '0001_initial'),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('overall', models.FloatField(verbose_name='overall')),
                ('premiere_date', models.DateField(blank=True, null=True, verbose_name='premiere date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='breweries.Brewery')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='styles.Style')),
            ],
            options={
                'verbose_name': 'beer',
                'verbose_name_plural': 'beers',
            },
        ),
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('overall', beerdiary_server.fields.RatingField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=16, verbose_name='overall')),
                ('bitterness', beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='bitterness')),
                ('bitterness_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='bitterness description')),
                ('foam', beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='foam')),
                ('foam_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='foam description')),
                ('ibu', models.PositiveIntegerField(blank=True, null=True, verbose_name='ibu')),
                ('color', models.CharField(blank=True, max_length=256, null=True, verbose_name='color')),
                ('aroma', beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='aroma')),
                ('aroma_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='aroma description')),
                ('taste', beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='taste')),
                ('taste_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='taste description')),
                ('palate', beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='palate')),
                ('palate_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='palate description')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beers.Beer')),
            ],
            options={
                'ordering': ('beer', 'created'),
                'verbose_name': 'beer review',
                'verbose_name_plural': 'beer reviews',
            },
        ),
    ]
