# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='aroma_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='aroma description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='bitterness_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='bitterness description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='color',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='foam_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='foam description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='palate_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='palate description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='taste_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='taste description'),
            preserve_default=False,
        ),
    ]
