version: '3'
services:
  postgres:
    image: postgres
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: uwsgi --ini=./compose/django/uwsgi.ini
    volumes:
      - .:/code
      - static:/static
    depends_on:
      - postgres
  web:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static:/static:ro
      - media:/media:ro
    depends_on:
      - django
    ports:
      - "80:80"
volumes:
  static:
    driver: local
  media:
    driver: local