version: '3'
services:
  postgres:
    image: postgres
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: python manage.py pytest
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - postgres
    networks:
      - default
