# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20170320_1915'),
        ('pub_visits', '0003_auto_20170409_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubvisit',
            name='beer',
        ),
        migrations.AddField(
            model_name='pubvisit',
            name='beers',
            field=models.ManyToManyField(related_name='pub_visits', to='beers.Beer', verbose_name='beers'),
        ),
    ]
