# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:48
from __future__ import unicode_literals

import beerdiary_server.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='atmosphere',
            field=beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='atmosphere'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='atmosphere_description',
            field=models.TextField(blank=True, null=True, verbose_name='atmosphere description'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='design',
            field=beerdiary_server.fields.SliderField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)), verbose_name='design'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='design_description',
            field=models.TextField(blank=True, null=True, verbose_name='design description'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='overall',
            field=beerdiary_server.fields.RatingField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=16, verbose_name='overall'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='street'),
        ),
    ]
