# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:48
from __future__ import unicode_literals

import beerdiary_server.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('overall', beerdiary_server.fields.RatingField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=16, null=True, verbose_name='overall')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'brewery',
                'verbose_name_plural': 'breweries',
            },
        ),
    ]
