# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='note'),
            preserve_default=False,
        ),
    ]
