# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubvisit',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
    ]
