# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_visits', '0002_auto_20170408_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubvisit',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
